import os

ARMA_TOOLS_APPID="233800"
ARMA_APPID="107410"
ACE_APPID="463939057"
INSTALL_DIR="/app/mods"
JSON_FILE_DB="/app/data.json"
AANM_APPID="2158809703"
STEAM_USERNAME=os.environ['STEAM_USERNAME']
STEAM_PASSWORD=os.environ['STEAM_PASSWORD']
GITHUB_USERNAME=os.environ['GITHUB_USERNAME']
GITHUB_TOKEN=os.environ['GITHUB_TOKEN']
