import os

ARMA_TOOLS_APPID="233800"
ARMA_APPID="107410"
ACE_APPID="463939057"
INSTALL_DIR="/app/mods"
JSON_FILE_DB="/app/data.json"
AANM_APPID="?"
STEAM_USERNAME=os.environ['STEAM_USERNAME']
STEAM_PASSWORD=os.environ['STEAM_PASSWORD']