name: Build and publish the mod

on:
  push:
    branches:
      - master
      - dev

jobs:
    build:
        runs-on: windows-latest
        timeout-minutes: 5
        steps:
        - name: Checkout the code
          uses: actions/checkout@master
    
        - name: Build addons
          run: '.\buildAddons.py'
    
        - name: Upload build addon artifact
          uses: actions/upload-artifact@v2
          with:
            name: addon
            path: addon/aanm.pbo

    publish:
        upload:
            runs-on: ubuntu-latest
            timeout-minutes: 10
            needs: [build]
        steps:
        - name: Download addon artifact
            uses: actions/download-artifact@v2
            with:
                name: addon
                path: addon
        - name: Publish to Steam Workshop
            uses: arma-actions/workshop-upload@v1
            with:
                appId: '107410'      # default
                itemId: '2158809703' # https://steamcommunity.com/sharedfiles/filedetails/?id=2158809703
                contentPath: 'addon'
                changelog: ''
            env:
                STEAM_USERNAME: ${{ secrets.STEAM_VIN_USER }}
                STEAM_PASSWORD: ${{ secrets.STEAM_VIN_PW }}