name: Build and publish the mod

on:
  push:
    branches:
      - master

jobs:
    build:
        runs-on: windows-latest
        timeout-minutes: 5
        steps:
        - name: Checkout the code
          uses: actions/checkout@master
    
        # - name: Build addon
        #   run: '.\tools\buildAddon.ps1'
    
        - name: Upload build addon artifact
          uses: actions/upload-artifact@v2
          with:
            name: armaAddon
            path: AANM

    publish:
        runs-on: ubuntu-latest
        timeout-minutes: 10
        needs: [build]
        steps:
        - name: Download addon artifact
          uses: actions/download-artifact@v2
          with:
              name: armaAddon
              path: armaAddon
        - name: Publish to Steam Workshop
          uses: arma-actions/workshop-upload@v1
          with:
              appId: '107410'      # default
              itemId: '2158809703' # https://steamcommunity.com/sharedfiles/filedetails/?id=2158809703
              contentPath: 'armaAddon'
              changelog: ''
          env:
              STEAM_USERNAME: ${{ secrets.STEAM_VIN_USER }}
              STEAM_PASSWORD: ${{ secrets.STEAM_VIN_PW }}